export function genPackageJson(cliName: string): string {
  return JSON.stringify(
    {
      name: cliName,
      version: '0.1.0',
      description: `CLI generated by api-cli-gen`,
      scripts: {
        build: 'node build.mjs',
      },
      dependencies: {
        axios: '^1.7.0',
        chalk: '^5.3.0',
        commander: '^12.1.0',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        esbuild: '^0.24.0',
        typescript: '^5.6.0',
      },
    },
    null,
    2,
  )
}
